[package]
name = "website"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]

[dependencies]
rocket = "0.3.5"
rocket_codegen = "0.3.5"
rocket_contrib = { version = "0.3.5", features = ["uuid", "tera_templates"] }
log = "0.4.0"
