[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
name = "website"
version = "0.1.0"

[dependencies]
bcrypt = "0.1"
dotenv = "0.10"
error-chain = "0.11"
r2d2 = "0.7.4"
r2d2-diesel = "0.16"
rocket = "0.3"
rocket_codegen = "0.3"
serde = "1.0.15"
serde_derive = "1.0"
serde_json = "1.0.3"
uuid = { version = "0.5.1", features = ["serde", "v4"] }
mongodb = "0.3"

[dependencies.rocket_contrib]
features = [
    "tera_templates",
    "json",
    "uuid",
]
version = "0.3"
