[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
name = "website"
version = "0.1.0"

[[bin]]
doc = false
name = "website"
path = "src/bin/server.rs"

[[bin]]
name = "website-cli"
path = "src/bin/cli.rs"

[dependencies]
bcrypt = "0.1"
bson = "0.9.1"
chrono = "0.4.0"
clap = "2.26.2"
dotenv = "0.10"
env_logger = "0.4.3"
error-chain = "0.11"
log = "0.3.8"
mongodb = "0.3"
r2d2 = "0.7.4"
r2d2-diesel = "0.16"
rocket = "0.3"
rocket_codegen = "0.3"
serde = "1.0.15"
serde_derive = "1.0"
serde_json = "1.0.3"

[dependencies.rocket_contrib]
features = [
    "tera_templates",
    "json",
    "uuid",
]
version = "0.3"

[dependencies.uuid]
features = [
    "serde",
    "v4",
]
version = "0.5.1"
