[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
description = "My personal website."
name = "website"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
clap = "2.27.1"
env_logger = "0.4.3"
log = "0.3.8"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_contrib = { version = "0.3.3", features = ["tera_templates", "uuid", "json"] }
serde = "1.0.17"
serde_derive = "1.0.17"
serde_json = "1.0.5"
