[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
name = "website"
version = "0.1.0"

[[bin]]
name = "website-server"
path = "src/bin/main.rs"

[dependencies]
bcrypt = "0.1.4"
dotenv = "0.10.1"
error-chain = "0.11"
r2d2 = "0.7.4"
r2d2-diesel = "0.16.0"
rocket = "0.3"
rocket_codegen = "0.3"

[dependencies.diesel]
features = ["postgres", "sqlite"]
version = "0.16"

[dependencies.diesel_codegen]
features = ["postgres", "sqlite"]
version = "0.16"
