version: '3'

services:
  website:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mongodb://mongo:27017"
    depends_on:
      - "mongo"
    networks:
      - db

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGODB_HOST: mongo
    networks:
      - db

networks:
  db:
