version: "3"
services:
  web:
    build: "."
    volumes:
      - "./:/code"
    depends_on:
      - "db"
    ports:
      - "8000:8000"
    environment:
      - "DATABASE_URL=postgres://postgres:postgres@db/postgres"
  db:
    image: "postgres:latest"
    environment:
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data: