version: '3'
services:
  website:
    build: .
    ports:
      - "5000"
    depends_on:
      - database
    environment:
      - ROCKET_ENV=production
      - ROCKET_PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@database/website
  database:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db-data:/var/lib/postgres
volumes:
    db-data:
