[package]
name = "website-cli"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]

[dependencies]
website = { path = ".." }
structopt = "0.1"
structopt-derive = "0.1"
failure = "0.1"
dotenv = "0.10"
log = "0.4"
env_logger = "0.5.0-rc.1"
serde_json = "1.0"
