table! {
    /// Representation of the `timesheet_entries` table.
    ///
    /// (Automatically generated by Diesel.)
    timesheet_entries (id) {
        /// The `id` column of the `timesheet_entries` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `user_id` column of the `timesheet_entries` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Int4>,
        /// The `start_time` column of the `timesheet_entries` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        start_time -> Nullable<Timestamp>,
        /// The `end_time` column of the `timesheet_entries` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        end_time -> Nullable<Timestamp>,
        /// The `breaks` column of the `timesheet_entries` table.
        ///
        /// Its SQL type is `Nullable<Float8>`.
        ///
        /// (Automatically generated by Diesel.)
        breaks -> Nullable<Float8>,
        /// The `morning` column of the `timesheet_entries` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        morning -> Nullable<Text>,
        /// The `afternoon` column of the `timesheet_entries` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        afternoon -> Nullable<Text>,
    }
}

table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `username` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        username -> Varchar,
        /// The `password_hash` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        password_hash -> Text,
        /// The `is_admin` column of the `users` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        is_admin -> Bool,
    }
}

allow_tables_to_appear_in_same_query!(
    timesheet_entries,
    users,
);
