---
- name: "Install Nginx"
  apt: pkg=nginx state=installed update_cache=true
  register: nginxinstalled
  notify:
    - Start Nginx

- name: "Make sure Nginx directories exist"
  file: dest="/etc/nginx/" mode=755 state=directory owner=root group=root
  notify:
    - Reload Nginx

- name: "Make sure Nginx conf.d directory exists"
  file: dest="/etc/nginx/conf.d/" mode=755 state=directory owner=root group=root
  notify:
    - Reload Nginx

- name: "Create Web root"
  when: nginxinstalled|success
  file: dest="/var/www/{{ domain }}" mode=775 state=directory owner=www-data group=www-data
  notify:
    - Reload Nginx

- name: "Web Root Permissions"
  when: nginxinstalled|success
  file: dest="/var/www/{{ domain }}" mode=775 state=directory owner=www-data group=www-data recurse=yes
  notify:
    - Reload Nginx

- name: "Copy across Nginx mime.types"
  template: src="mime.types" dest="/etc/nginx/mime.types"
  notify:
    - Reload Nginx

- name: "Copy across global Nginx config"
  template: src="nginx.conf" dest="/etc/nginx/nginx.conf"
  notify:
    - Reload Nginx

- name: "Copy across Nginx config file for the website"
  template: src="{{ domain }}" dest="/etc/nginx/conf.d/{{ domain }}"
  notify:
    - Reload Nginx
