# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_time_lunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='afternoon_task',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='time',
            name='morning_task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
