# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0007_timeslice_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslice',
            name='can_view_tasks',
        ),
    ]
