// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenState int32

const (
	// The token is empty, corrupted (e.g. encrypted with the wrong key), or
	// otherwise invalid.
	TokenState_InvalidToken TokenState = 0
	// The token is valid and currently active.
	TokenState_Active TokenState = 1
	// The token was valid, but has since expired.
	TokenState_Expired TokenState = 2
)

var TokenState_name = map[int32]string{
	0: "InvalidToken",
	1: "Active",
	2: "Expired",
}

var TokenState_value = map[string]int32{
	"InvalidToken": 0,
	"Active":       1,
	"Expired":      2,
}

func (x TokenState) String() string {
	return proto.EnumName(TokenState_name, int32(x))
}

func (TokenState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	JwtToken             string   `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetJwtToken() string {
	if m != nil {
		return m.JwtToken
	}
	return ""
}

type LogoutRequest struct {
	JwtToken             string   `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetJwtToken() string {
	if m != nil {
		return m.JwtToken
	}
	return ""
}

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type DescribeTokenRequest struct {
	JwtToken             string   `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeTokenRequest) Reset()         { *m = DescribeTokenRequest{} }
func (m *DescribeTokenRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeTokenRequest) ProtoMessage()    {}
func (*DescribeTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *DescribeTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeTokenRequest.Unmarshal(m, b)
}
func (m *DescribeTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeTokenRequest.Marshal(b, m, deterministic)
}
func (m *DescribeTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeTokenRequest.Merge(m, src)
}
func (m *DescribeTokenRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeTokenRequest.Size(m)
}
func (m *DescribeTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeTokenRequest proto.InternalMessageInfo

func (m *DescribeTokenRequest) GetJwtToken() string {
	if m != nil {
		return m.JwtToken
	}
	return ""
}

type TokenDescription struct {
	State                TokenState           `protobuf:"varint,1,opt,name=state,proto3,enum=TokenState" json:"state,omitempty"`
	UserName             string               `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Expires              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TokenDescription) Reset()         { *m = TokenDescription{} }
func (m *TokenDescription) String() string { return proto.CompactTextString(m) }
func (*TokenDescription) ProtoMessage()    {}
func (*TokenDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *TokenDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenDescription.Unmarshal(m, b)
}
func (m *TokenDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenDescription.Marshal(b, m, deterministic)
}
func (m *TokenDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenDescription.Merge(m, src)
}
func (m *TokenDescription) XXX_Size() int {
	return xxx_messageInfo_TokenDescription.Size(m)
}
func (m *TokenDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenDescription.DiscardUnknown(m)
}

var xxx_messageInfo_TokenDescription proto.InternalMessageInfo

func (m *TokenDescription) GetState() TokenState {
	if m != nil {
		return m.State
	}
	return TokenState_InvalidToken
}

func (m *TokenDescription) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TokenDescription) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *TokenDescription) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

func init() {
	proto.RegisterEnum("TokenState", TokenState_name, TokenState_value)
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "LogoutResponse")
	proto.RegisterType((*DescribeTokenRequest)(nil), "DescribeTokenRequest")
	proto.RegisterType((*TokenDescription)(nil), "TokenDescription")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x49, 0xd8, 0x3a, 0x72, 0xb2, 0x76, 0x99, 0xc5, 0x50, 0x14, 0x90, 0x18, 0xb9, 0x9a,
	0x26, 0xe4, 0x4a, 0x1d, 0x12, 0x12, 0x12, 0x17, 0x95, 0x00, 0x09, 0x69, 0xe2, 0x22, 0xec, 0x7e,
	0x72, 0x1b, 0x13, 0x3c, 0x5a, 0xdb, 0xc4, 0x27, 0x2d, 0xd7, 0xbc, 0x02, 0xef, 0xc3, 0x4b, 0x20,
	0xf1, 0x04, 0x3c, 0x08, 0xb2, 0x1d, 0x53, 0x5a, 0x21, 0xe0, 0x2e, 0xc7, 0xff, 0x7f, 0xbe, 0x24,
	0xff, 0x6f, 0x48, 0x98, 0x16, 0x54, 0xb7, 0x0a, 0x55, 0xf1, 0xa0, 0x51, 0xaa, 0x59, 0xf0, 0x31,
	0xd3, 0x62, 0xcc, 0xa4, 0x54, 0xc8, 0x50, 0x28, 0x69, 0x7a, 0xf5, 0x61, 0xaf, 0xba, 0x69, 0xd6,
	0xbd, 0x1b, 0xa3, 0x58, 0x72, 0x83, 0x6c, 0xa9, 0xbd, 0xa1, 0x7c, 0x05, 0x87, 0x97, 0xaa, 0x11,
	0xb2, 0xe2, 0x1f, 0x3b, 0x6e, 0x90, 0x14, 0x70, 0xa7, 0x33, 0xbc, 0x95, 0x6c, 0xc9, 0xf3, 0xe8,
	0x34, 0x3a, 0x4b, 0xaa, 0x5f, 0xb3, 0xd5, 0x34, 0x33, 0x66, 0xad, 0xda, 0x3a, 0x8f, 0xbd, 0x16,
	0xe6, 0xf2, 0x31, 0x0c, 0x7b, 0x8e, 0xd1, 0x4a, 0x1a, 0x4e, 0xee, 0x43, 0x72, 0xb3, 0xc6, 0x6b,
	0x54, 0x1f, 0xb8, 0x0c, 0xa4, 0x9b, 0x35, 0x5e, 0xd9, 0xb9, 0x77, 0xab, 0x0e, 0xc3, 0x6b, 0xff,
	0xea, 0xce, 0x60, 0x14, 0xdc, 0x1e, 0x5e, 0x5e, 0xc0, 0xdd, 0x17, 0xdc, 0xcc, 0x5b, 0x31, 0xe3,
	0xce, 0xf2, 0x5f, 0x98, 0xaf, 0x11, 0x64, 0xee, 0xc9, 0xaf, 0x6a, 0x9b, 0x13, 0x79, 0x04, 0xfb,
	0x06, 0x19, 0xfa, 0x9f, 0x1d, 0x4d, 0x52, 0xea, 0x1c, 0x6f, 0xed, 0x51, 0xe5, 0x15, 0x0b, 0xb5,
	0x11, 0x5c, 0xbb, 0x4c, 0xe2, 0x4d, 0x26, 0x6f, 0x6c, 0x26, 0x4f, 0xe0, 0x60, 0xde, 0x72, 0x86,
	0xbc, 0xce, 0x6f, 0x9f, 0x46, 0x67, 0xe9, 0xa4, 0xa0, 0x3e, 0x72, 0x1a, 0x22, 0xa7, 0x57, 0x21,
	0xf2, 0x2a, 0x58, 0xed, 0x16, 0xff, 0xa4, 0x45, 0xcb, 0x4d, 0xbe, 0xf7, 0xef, 0xad, 0xde, 0x7a,
	0xfe, 0x14, 0x60, 0xf3, 0x75, 0x24, 0x83, 0xc3, 0xd7, 0x72, 0xc5, 0x16, 0xa2, 0x76, 0x87, 0xd9,
	0x2d, 0x02, 0x30, 0x98, 0xce, 0x51, 0xac, 0x78, 0x16, 0x91, 0x14, 0x0e, 0x5e, 0xba, 0xb5, 0x3a,
	0x8b, 0x27, 0xdf, 0x23, 0xd8, 0x9b, 0x76, 0xf8, 0x9e, 0x3c, 0x87, 0x7d, 0xd7, 0x12, 0x19, 0xd2,
	0xdf, 0x5b, 0x2f, 0x46, 0x74, 0xab, 0xbc, 0xf2, 0xe4, 0xf3, 0xb7, 0x1f, 0x5f, 0xe2, 0xa3, 0x12,
	0xdc, 0xb5, 0x5a, 0x58, 0xed, 0x59, 0x74, 0x4e, 0xa6, 0x30, 0xf0, 0x45, 0x10, 0xb7, 0xb0, 0xe9,
	0xaf, 0x38, 0xa2, 0x3b, 0x0d, 0xdd, 0x73, 0x84, 0xac, 0x4c, 0x03, 0x41, 0x75, 0x68, 0x11, 0x97,
	0x30, 0xdc, 0x6a, 0x8e, 0x9c, 0xd0, 0x3f, 0x35, 0x59, 0x1c, 0xd3, 0xdd, 0xaa, 0xca, 0x63, 0x87,
	0x4c, 0x49, 0xe2, 0x90, 0x5a, 0xc8, 0x66, 0x36, 0x70, 0x71, 0x5d, 0xfc, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0xf9, 0xa4, 0x17, 0x82, 0x10, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	// Login attempts to authenticate the user.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Logout ends the user's session.
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	DescribeToken(ctx context.Context, in *DescribeTokenRequest, opts ...grpc.CallOption) (*TokenDescription, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/Auth/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) DescribeToken(ctx context.Context, in *DescribeTokenRequest, opts ...grpc.CallOption) (*TokenDescription, error) {
	out := new(TokenDescription)
	err := c.cc.Invoke(ctx, "/Auth/DescribeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	// Login attempts to authenticate the user.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Logout ends the user's session.
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	DescribeToken(context.Context, *DescribeTokenRequest) (*TokenDescription, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_DescribeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).DescribeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/DescribeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).DescribeToken(ctx, req.(*DescribeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Auth_Logout_Handler,
		},
		{
			MethodName: "DescribeToken",
			Handler:    _Auth_DescribeToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
